### ISSUE TITLE
[bug]: Bundle ID not found on Allowlist - Please verify that your bundle ID is allowed at https://cloud.reown.com

### ISSUE THREAD

**Issue by itsnyx** [reown-com/appkit-react-native#296]
### Description

Hello, i updated my project to use the new reown package instead of old one but i keep getting this error 
the wallets list loads but i can't connect to them. also the qr code dosen't work ! 

i already added my bundles to the cloud but not working !

![image](https://github.com/user-attachments/assets/b69c63db-8e7a-428c-be00-ef0a6572251e)

### AppKit SDK version

    "@reown/appkit-wagmi-react-native": "^1.1.1",

### Output of `npx react-native info`

```
System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 5600H with Radeon Graphics         "
  Memory: 2.75 GB / 15.86 GB
Binaries:
  Node:
    version: 20.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman:
    version: 20240728.093121.0
    path: C:\ProgramData\chocolatey\bin\watchman.EXE
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-31 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
      - android-35 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-242.23339.11.2421.12483815
  Visual Studio:
    - 17.11.35312.102 (Visual Studio Community 2022)
Languages:
  Java: 17.0.11
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

import '@walletconnect/react-native-compat';
import {WagmiProvider} from 'wagmi';
import {mainnet, polygon, arbitrum} from '@wagmi/core/chains';
import {QueryClient, QueryClientProvider} from '@tanstack/react-query';
import {
  createAppKit,
  defaultWagmiConfig,
  AppKit,
  AppKitButton,
} from '@reown/appkit-wagmi-react-native';

// 0. Setup queryClient
const queryClient = new QueryClient();

// 1. Get projectId at https://cloud.reown.com
const projectId = 'MY_PROJECT_ID';

// 2. Create config
const metadata = {
  name: 'Soroosh App',
  description: 'AppKit Example',
  url: 'https://domain.com', // origin must match your domain & subdomain
  icons: ['https://assets.reown.com/reown-profile-pic.png'],
};
const chains = [mainnet, polygon, arbitrum] as const;

const wagmiConfig = defaultWagmiConfig({chains, projectId, metadata});

// 3. Create modal
createAppKit({
  projectId,
  wagmiConfig,
  defaultChain: mainnet, // Optional
  enableAnalytics: true, // Optional - defaults to your Cloud configuration
});

export default function App() {
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <AppKitButton />
        <AppKit />
      </QueryClientProvider>
    </WagmiProvider>
  );
}

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/user-attachments/assets/430c5b88-6720-49d8-93ba-0c1443c513fd)
![image](https://github.com/user-attachments/assets/39dfed8a-2aca-4191-beaa-6b5b6d13fefa)

**Comment by itsnyx** [comment]
![image](https://github.com/user-attachments/assets/96ec66d6-1610-4aa4-8e91-bc085a16ba32)
this is the only domain we have 

and these are bundle ids : 

![image](https://github.com/user-attachments/assets/9036e983-2f8c-4777-930a-5f1f5b843fd8)

**Comment by Derrick-Fix** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by itsnyx** [comment]
i added my app bundle ids to the domains list as mentioned in https://github.com/reown-com/appkit-react-native/issues/224#issuecomment-2457739606 

it would be awesome to update the doc to mention this or make it so we don't added it to the domains list to save time :D

thanks for the great library
